#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
bash_completion_dir="${repo_root}/dot_config/completion/bash"
zsh_completion_dir="${repo_root}/dot_config/completion/zsh"

BASH_MANAGED_PREFIX="aqua-"
ZSH_MANAGED_PREFIX="_aqua_"

mkdir -p "${bash_completion_dir}" "${zsh_completion_dir}"

sanitize_name() {
  local value="$1"
  value="${value//[^A-Za-z0-9_.-]/_}"
  printf '%s\n' "${value}"
}

write_bash_completion() {
  local command_name="$1"
  local content="$2"
  local safe_name
  safe_name="$(sanitize_name "${command_name}")"
  local output_file="${bash_completion_dir}/${BASH_MANAGED_PREFIX}${safe_name}.bash.tmpl"

  {
    echo "# generated by .github/scripts/refresh-shell-completions.sh"
    echo "# source command: ${command_name}"
    echo
    printf '%s\n' "${content}"
  } >"${output_file}"
}

write_zsh_completion() {
  local command_name="$1"
  local content="$2"
  local safe_name
  safe_name="$(sanitize_name "${command_name}")"
  local output_file="${zsh_completion_dir}/${ZSH_MANAGED_PREFIX}${safe_name}.tmpl"

  {
    echo "# generated by .github/scripts/refresh-shell-completions.sh"
    if ! grep -qE '^#compdef[[:space:]]' <<<"${content}"; then
      echo "#compdef ${command_name}"
    fi
    echo
    printf '%s\n' "${content}"
  } >"${output_file}"
}

run_completion_command() {
  local command_name="$1"
  local command_path="$2"
  local shell_name="$3"
  shift 3

  local output
  if output="$("${command_path}" "$@" 2>/dev/null)" && [[ -n "${output}" ]]; then
    if [[ "${shell_name}" == "bash" ]]; then
      write_bash_completion "${command_name}" "${output}"
    else
      write_zsh_completion "${command_name}" "${output}"
    fi
    return 0
  fi

  return 1
}

generate_completion_for_shell() {
  local command_name="$1"
  local command_path="$2"
  local shell_name="$3"

  run_completion_command "${command_name}" "${command_path}" "${shell_name}" completion "${shell_name}" && return 0
  run_completion_command "${command_name}" "${command_path}" "${shell_name}" completions "${shell_name}" && return 0
  run_completion_command "${command_name}" "${command_path}" "${shell_name}" completion --shell "${shell_name}" && return 0
  run_completion_command "${command_name}" "${command_path}" "${shell_name}" --generate-completion "${shell_name}" && return 0
  run_completion_command "${command_name}" "${command_path}" "${shell_name}" --completion-"${shell_name}" && return 0

  return 1
}

collect_aqua_commands() {
  local aqua_bin="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-${HOME}/.local/share}/aquaproj-aqua}/bin"
  [[ -d "${aqua_bin}" ]] || return 0

  local path_entry
  for path_entry in "${aqua_bin}"/*; do
    [[ -x "${path_entry}" && -f "${path_entry}" ]] || continue
    printf '%s\t%s\n' "$(basename "${path_entry}")" "${path_entry}"
  done | LC_ALL=C sort -u
}

refresh_chezmoi_completion() {
  local output

  if ! command -v chezmoi >/dev/null 2>&1; then
    echo "Skipping chezmoi completion refresh: chezmoi not available" >&2
    return 0
  fi

  if output="$(chezmoi completion bash 2>/dev/null)" && [[ -n "${output}" ]]; then
    printf '%s\n' "${output}" >"${bash_completion_dir}/chezmoi.bash.tmpl"
  fi

  if output="$(chezmoi completion zsh 2>/dev/null)" && [[ -n "${output}" ]]; then
    printf '%s\n' "${output}" >"${zsh_completion_dir}/_chezmoi.tmpl"
  fi
}

rm -f "${bash_completion_dir}/${BASH_MANAGED_PREFIX}"*.bash.tmpl
rm -f "${zsh_completion_dir}/${ZSH_MANAGED_PREFIX}"*.tmpl

refresh_chezmoi_completion

while IFS=$'\t' read -r command_name command_path; do
  [[ -n "${command_name}" ]] || continue
  generate_completion_for_shell "${command_name}" "${command_path}" bash || true
  generate_completion_for_shell "${command_name}" "${command_path}" zsh || true
done < <(collect_aqua_commands)

