# nredf configuration (YAML)
# Edit this file and run ~/.local/bin/generate_nredf_config.sh or run "chezmoi apply" after templating.

Multiplexer: true
_nredf_tool_btop: true
_nredf_tool_atuin: true
_nredf_tool_ctop: true
_nredf_tool_diskus: true
_nredf_tool_duf: true
_nredf_tool_dust: true
_nredf_tool_fd: true
_nredf_tool_fzf: true
_nredf_tool_githubcli: true
_nredf_tool_helix: true
_nredf_tool_jq: true
_nredf_tool_lazygit: true
_nredf_tool_lsd: true
_nredf_tool_ouch: true
_nredf_tool_q: true
_nredf_tool_ripgrep: true
_nredf_tool_yazi: true
_nredf_tool_yq: true
_nredf_tool_zellij: true
_nredf_tool_kubectl: false
_nredf_tool_krew: false
_nredf_tool_kubeadm: false
_nredf_tool_kubeseal: false
_nredf_tool_fluxctl: false
_nredf_tool_flux: false
_nredf_tool_helm: false
_nredf_tool_oras: false
_nredf_tool_k9s: false
_nredf_tool_velero: false
_nredf_tool_kustomize: false
_nredf_tool_stern: false
_nredf_tool_step: true
_nredf_tool_calico: false
_nredf_tool_kubent: false
_nredf_tool_bw: false
AGENT_PIPE: false
AGENT_GPG: false
AGENT_BITWARDEN: false
SSH_TOTP_PROVIDER: "#bitwarden"
